# Generated by Django 4.0.5 on 2022-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productoption_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=1),
        ),
    ]
