# Generated by Django 4.0.5 on 2022-07-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_delete_subcategory_delete_topcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
